version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.2
    - 1.440.4
    - 1.440.5
    - 1.445.0
    - 1.446.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.460.0
    - 1.463.0
    - 1.464.0
    - 1.467.0
    - 1.472.0
    - 1.476.0
    - 1.477.0
    - 1.479.0
    - 1.483.0
    - 1.487.0
    - 1.489.0
    - 1.490.0
    - 1.493.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.506.0
    - 1.509.0
    - 1.512.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.529.0
    - 1.531.0
    - 1.534.0
    - 1.539.0
    - 1.542.0
    - 1.559.0
    - 1.563.0
    - 1.564.0
    - 1.567.0
    - 1.570.0
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
    - 6.3.2
  - dependency-name: "@babel/node"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
  - dependency-name: chromedriver
    versions:
    - 88.0.0
    - 89.0.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: stylelint-scss
    versions:
    - 3.18.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: eslint-plugin-you-dont-need-lodash-underscore
    versions:
    - 6.10.0
